# ServiceAccounts cho các service cần kiểm soát Authorization Policy
# Istio sử dụng ServiceAccount để xác định danh tính (identity) của Pod
# Mỗi service cần có ServiceAccount riêng để phân biệt với nhau
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cart
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: media
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: location
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tax
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rating
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promotion
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storefront-bff
  namespace: yas-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backoffice-bff
  namespace: yas-dev
